server:
  port: 8100
---
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
---
spring:
  application:
    name: keycloak
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=spring-class
    username: postgres
    password: 123456aA@
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
    tomcat:
      initial-size: 20
      max-wait: 25000
      max-active: 70
      max-idle: 20
      min-idle: 9
      default-auto-commit: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: off
    hibernate:
      ddl-auto: update
---
keycloak-client:
  client-id: cmc-resource-mngt
  client-secret: Ixh7s4oFZmTuIuiAmiB1sMZiStM5grAm
---
keycloak:
  realm: resource-mngt
  auth-server-url: http://192.168.66.41:8180/auth
  ssl-required: external
  resource: cmc-resource-mngt
  bearer-only: true