server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: users